Repository ezsystems/ezplatform-content-forms, pull requests merged in 2020-04, with the labels that each got.

#20 EZP-30543: Removed Dynamic Settings functionality from kernel
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/views.yaml
  src/lib/Content/View/Builder/ContentCreateViewBuilder.php
  src/lib/Content/View/Builder/ContentEditViewBuilder.php
  src/lib/EventListener/ViewTemplatesListener.php
Labels: enhancement

#23 EZP-31317: Loaded ContentType using preferred language in UserController
  src/bundle/Controller/UserController.php
  src/bundle/Resources/config/services.yaml
Labels: Bug, QA approved

#24 EZP-31572: Dropped deprecated data class
  src/lib/Data/ContentTranslationData.php
  src/lib/Data/User/UserRegisterData.php
Labels: QA approved

#22 EZP-31542: Added PHP 7.4 support (eZ Platform 3.0)
  .travis.yml
  src/lib/FieldType/DataTransformer/SingleCountryValueTransformer.php
  src/lib/Tests/FieldType/DataTransformer/SingleCountryValueTransformerTest.php
Labels: Improvement, QA approved
